services:
  flask-app:
    build: .
    ports:
      - "80:80"

  test:
    build: .
    command: >
      sh -c "python3 -m pytest ./tests --cov=. --junitxml=./xmlReport/output.xml && 
             python3 -m coverage xml"
    depends_on:
      - flask-app
    networks:
      - demo_python_flask

networks:
  demo_python_flask:
